name: Java CI with Gradle
on:
  workflow_dispatch:
    inputs:
      update:
        type: boolean
        description: Update the version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service PTIT_OOP
        env:
          RAILWAY_TOKEN = ${{ secrets.RAILWAY_TOKEN }}
